# Generated by Django 5.0.2 on 2024-04-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customercoupon"),
        ("payment", "0004_transaction_address_transaction_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.customer",
            ),
        ),
    ]
