# Generated by Django 4.2.10 on 2024-03-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'InActive')], max_length=8)),
                ('product', models.ManyToManyField(to='product.product')),
                ('product_tag', models.ManyToManyField(to='product.producttag')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('1', 'Discount'), ('2', 'Free shipment'), ('3', 'New user')], max_length=8)),
                ('discount_amount', models.IntegerField()),
                ('discount_type', models.CharField(choices=[('1', 'Discount'), ('2', 'Free shipment'), ('3', 'New user')], max_length=8)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'InActive'), ('3', 'Hidden')], max_length=8)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.couponcondition')),
            ],
        ),
    ]
