# Generated by Django 5.0.2 on 2024-03-01 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
        ("payment", "0003_transaction_coupon_alter_transaction_status_and_more"),
        ("product", "0002_alter_productstock_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.productdetail",
            ),
        ),
    ]
