# Generated by Django 5.0.2 on 2024-04-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customercoupon"),
        ("payment", "0003_transaction_coupon_alter_transaction_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.address",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="discount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="total",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
